zuul:
  routes:
    profileService:
      serviceId: P2PDINNER-PROFILE-SERVICES
      stripPrefix: false
    catalogService:
      serviceId: P2PDINNER-MENU-SERVICES
      stripPrefix: false
---      
spring:
  profiles: development


