feign:
  hystrix:
    enabled: false
---      
spring:
  profiles: development
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST}
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
  profiles: kube
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/catalogdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: 10.0.0.3
    port: 6379
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
