eureka:
  client:
    fetchRegistry: true
zuul:
  routes:
    profileService:
      path: /p2pdinner/profiles/**
      serviceId: P2PDINNER-PROFILE-SERVICES
      stripPrefix: false
---      
spring:
  profiles: development


