zuul:
  routes:
    profileService:
      path: /**
      serviceId: P2PDINNER-PROFILE-SERVICES
      stripPrefix: false
    catalogService:
      path: /**
      serviceId: P2PDINNER-MENU-SERVICES
      stripPrefix: false
---      
spring:
  profiles: development
  cloud:
    config:
      uri: http://config-service:8888/
      fail-fast: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8010/eureka
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


