eureka:
  client:
    fetchRegistry: true
zuul:
  routes:
    profileService:
      path: /p2pdinner/profiles/**
      url: http://35.192.47.56:80/
      stripPrefix: false
---      
spring:
  profiles: development


