logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core: DEBUG
grpc:
  port: 6565
eureka:
  instance:
    nonSecurePort: ${grpc.port}
---
spring:
  profiles: local
  data:
    mongodb:
      authenticaiton-database: admin
      database: listings
      host: localhost
      port: 27017
---      
spring:
  profiles: development
  data:
    mongodb:
      authentication-database: admin
      database: listings
      host: document-server
      port: 27017
  rabbitmq:
    host: message-broker
logging:
  level:
    org.springframework.security: DEBUG