eureka:
  client:
    fetchRegistry: false
ribbon:
  eureka:
    enabled: false
zuul:
  routes:
    profileService:
      path: /profiles/**
      url: http://35.192.47.56:80/api/profiles
      stripPrefix: false
---      
spring:
  profiles: development


