server:
  port: ${PORT:${SERVER_PORT:0}}
---      
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogdb
    username: rajaniy
    password: 1800$heemu
  jpa:
    hibernate:
      ddl-auto: update
feign:
  hystrix:
    enabled: false
logging:
  level:
    org.springframework.security: DEBUG
