---      
spring:
  profiles: development
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: kube
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
---      
spring:
  profiles: kube
  datasource:
    url: jdbc:postgresql://google/profiledb?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=glowing-vehicle-220016:us-central1:profile-services-datastore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: cloud
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG

