---      
spring:
  profiles: local
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    preferIpAddress: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
---      
spring:
  profiles: development
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: message-broker
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
  profiles: kube
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/catalogdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    host: 10.0.0.3
    port: 6379
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
