eureka:
  client:
    fetchRegistry: true
zuul:
  routes:
    profileService:
      path: /profiles/**
      url: http://35.192.47.56:80/api/profiles
      stripPrefix: false
---      
spring:
  profiles: development


