---
spring:
  profiles: local
  data:
    mongodb:
      authenticaiton-database: admin
      database: listings
      host: localhost
      port: 27017
  rabbitmq:
    host: message-broker
logging:
  level:
    org.springframework.security: DEBUG
---      
spring:
  profiles: development
  data:
    mongodb:
      authenticaiton-database: admin
      database: listings
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
  rabbitmq:
    host: message-broker
logging:
  level:
    org.springframework.security: DEBUG